[package]
name = "comp6453_rust_sphincs"        
version = "0.1.0"                
edition = "2024"                  

[dependencies]
# tiny-keccak SHAKE256
tiny-keccak = { version = "2.0", features = ["shake"] }

rand = "0.8"
rand_core = "0.6"